
 export const productData = [ 
    {
      "id":Math.floor(Math.random()*100000000),
      "img_url": 'https://naturals.pk/cdn/shop/products/unnamed_360x.jpg?v=1614235688',
      "title": "Apple",
      "description": " are a sweet and crunchy fruit that are a good source of fiber and vitamins. They can be eaten fresh, cooked, or juiced. Apples are a popular choice for snacks and desserts.",
      "price": 2.99,
      "category": "Fruit"
    },
    {
      "id":Math.floor(Math.random()*100000000),
      "img_url": 'https://naturals.pk/cdn/shop/products/guava_360x.jpg?v=1588214165',
      "title": "Guava",
      "description": "are a convenient and nutritious snack that are a good source of potassium and fiber. They can be eaten fresh, frozen, or cooked. Bananas are a popular choice for breakfast, smoothies, and baking.",
      "price": 1.49,
      "category": "Fruit"
    },
    {
      "id":Math.floor(Math.random()*100000000),
      "img_url": 'https://naturals.pk/cdn/shop/products/apple-kalakulu_360x.jpg?v=1593218784',
      "title":"Kalakulu Apple",
      "description": "are a refreshing and healthy citrus fruit that are a good source of vitamin C. They can be eaten fresh, juiced, or used in cooking. Oranges are a popular choice for breakfast and snacks.",
      "price": 1.99,
      "category": "Fruit"
    },
    {
      "id":Math.floor(Math.random()*100000000),
      "img_url": 'https://naturals.pk/cdn/shop/products/apple-royal-gala-1_360x.jpg?v=1588214100',
      "title": "Apple Royal",
      "description": "are a versatile Fruits that can be eaten in many different ways. They are a good source of potassium and vitamin C. Potatoes can be roasted, mashed, fried, or baked.",
      "price": 1.29,
      "category": "Fruits",
      "stock":true,
    },
    {
      "id":Math.floor(Math.random()*100000000),
      "img_url": 'https://naturals.pk/cdn/shop/products/banana_360x.jpg?v=1588214106',
      "title": "Banana",
      "description": " are a crunchy and nutritious root Fruits that are a good source of beta-carotene and vitamin A. They can be eaten raw, cooked, or juiced.  are a popular choice for snacks and salads.",
      "price": 1.49,
      "category": "Fruits",
      "stock":true,
    },
    {
      "id":Math.floor(Math.random()*100000000),
      "img_url": 'https://naturals.pk/cdn/shop/products/apple-safaid_360x.jpg?v=1588214103',
      "title": "White Apple",
      "description": " are a crunchy and nutritious root Fruits that are a good source of beta-carotene and vitamin A. They can be eaten raw, cooked, or juiced.  are a popular choice for snacks and salads.",
      "price": 1.49,
      "category": "Fruits",
      "stock":true,
    },
     {
      "id":Math.floor(Math.random()*100000000),
      "img_url": 'https://naturals.pk/cdn/shop/products/grocerapp-papaya--5f0816d11d3aa_360x.jpg?v=1631373896',
      "title": "Papaya",
      "description": " are a crunchy and nutritious root Fruits that are a good source of beta-carotene and vitamin A. They can be eaten raw, cooked, or juiced.  are a popular choice for snacks and salads.",
      "price": 1.49,
      "category": "Fruits",
      "stock":true,
    },
     {
      "id":Math.floor(Math.random()*100000000),
      "img_url": 'https://naturals.pk/cdn/shop/products/pomegranate-kandhari_360x.jpg?v=1588214106',
      "title": "Pomegranate",
      "description": " are a crunchy and nutritious root Fruits that are a good source of beta-carotene and vitamin A. They can be eaten raw, cooked, or juiced.  are a popular choice for snacks and salads.",
      "price": 1.49,
      "category": "Fruits",
      "stock":true,
    },
     {
      "id":Math.floor(Math.random()*100000000),
      "img_url": 'https://naturals.pk/cdn/shop/products/water-melon_360x.jpg?v=1589056228',
      "title": "Watermelon",
      "description": " are a crunchy and nutritious root Fruits that are a good source of beta-carotene and vitamin A. They can be eaten raw, cooked, or juiced.  are a popular choice for snacks and salads.",
      "price": 1.49,
      "category": "Fruits",
      "stock":true,
    },
     {
      "id":Math.floor(Math.random()*100000000),
      "img_url": 'https://naturals.pk/cdn/shop/products/orange-shakri_46a5407f-b83d-40b1-ba98-a35f42061f09_360x.jpg?v=1606199137',
      "title": "Orange",
      "description": " are a crunchy and nutritious root Fruits that are a good source of beta-carotene and vitamin A. They can be eaten raw, cooked, or juiced.  are a popular choice for snacks and salads.",
      "price": 1.49,
      "category": "Fruits",
      "stock":false,
    },
     {
      "id":Math.floor(Math.random()*100000000),
      "img_url": "https://naturals.pk/cdn/shop/products/mango-dosehri_360x.jpg?v=1588214065",
      "title": "Mango Dosehri",
      "description": " are a crunchy and nutritious root Fruits that are a good source of beta-carotene and vitamin A. They can be eaten raw, cooked, or juiced.  are a popular choice for snacks and salads.",
      "price": 1.49,
      "category": "Fruits",
      "stock":true,
    },
     {
      "id":Math.floor(Math.random()*100000000),
      "img_url": 'https://naturals.pk/cdn/shop/products/mango-dosehri_360x.jpg?v=1588214065',
      "title": "Mango",
      "description": " are a crunchy and nutritious root Fruits that are a good source of beta-carotene and vitamin A. They can be eaten raw, cooked, or juiced.  are a popular choice for snacks and salads.",
      "price": 1.49,
      "category": "Fruits",
      "stock":true,
    },
     {
      "id":Math.floor(Math.random()*100000000),
      "img_url": 'https://naturals.pk/cdn/shop/products/cherry_360x.jpg?v=1588214152',
      "title": "Cherry",
      "description": " are a crunchy and nutritious root Fruits that are a good source of beta-carotene and vitamin A. They can be eaten raw, cooked, or juiced.  are a popular choice for snacks and salads.",
      "price": 1.49,
      "category": "Fruits",
      "stock":false,
    },
     {
      "id":Math.floor(Math.random()*100000000),
      "img_url": 'https://naturals.pk/cdn/shop/products/prune.jpg?v=1588214062',
      "title": "Plum",
      "description": " are a crunchy and nutritious root Fruits that are a good source of beta-carotene and vitamin A. They can be eaten raw, cooked, or juiced.  are a popular choice for snacks and salads.",
      "price": 1.49,
      "category": "Fruits",
      "stock":true,
    }
  ]